inactive_posts_job:
  cron: "0 3 * * *" # the job will be executed every day at 3:00 am
  class: "InactivePostsJob"
  queue: default

daily_posts_job:
  cron: "0 6 * * *"
  class: "DailyPostsJob"
  queue: default
