version: '3'

volumes:
  db-data:
    external: false
  redis-data:
    external: false
  es-data:
    external: false

services:
  db:
    image: postgres:9.6.4-alpine
    env_file: .env
    volumes:
      - 'db-data:/var/lib/postgresql/db-data'
  trip_tippa_app:
    build: .
    env_file: .env
    volumes:
      - .:/usr/src/trip_tippa
    ports:
      - "3000:3000"
    links:
      - db
      - redis
      - elasticsearch
      - sidekiq
    tty: true
    stdin_open: true
  redis:
    image: redis:3.2.10-alpine
    ports:
      - '6379:6379'
    volumes:
      - 'redis-data:/var/lib/redis/data'
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/trip_tippa
    env_file: .env
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    volumes:
      - "es-data:/usr/share/elasticsearch/data"
    env_file: .env
