source 'https://rubygems.org'
ruby '2.4.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '5.1.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'paperclip'

gem 'will_paginate', '~> 3.1.0'

gem 'riddle'

gem 'redis', '~> 3.2'
gem 'sidekiq' # background processing for Ruby
gem "sidekiq-cron", "~> 0.4.0"

gem 'puma', '~> 3.0'

gem 'local_time' # for displaying times and dates to users in their local time
gem "cocoon" # Dynamic nested forms

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'binding.pry' anywhere in the code to stop execution and get a debugger console
  gem 'pry-byebug'
  gem 'pry-rails'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'listen', '~> 3.0.5'
end

# Authentication
gem 'google-api-client', '~> 0.11'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'devise'
gem 'omniauth-google-oauth2'

# Authorization
gem "pundit"

# Facebook API
gem "koala"

# Elasticsearch interface
gem 'searchkick'

# Gems for Google Places and Geocoder
gem 'geocoder'

# Simplify Rails app configuration
gem 'figaro'

# Use unicorn as the app server
# gem 'unicorn'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

gem 'font-awesome-sass'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
group :development, :test do
  gem 'rspec', '3.5'
  gem 'rspec-rails', '3.5'
  gem 'rspec-context-private', '0.0.1'
  gem 'rspec-html-matchers', '0.6.1'
end
